services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_HTTP_PORTS: 80
    networks:
      - internal
    depends_on:
      - db
  worker:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    networks:
      - internal
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      ACCEPT_EULA: Y 
      MSSQL_SA_PASSWORD: 12345Abç
      MSSQL_PID: Express
    volumes:
        - ./init.sql:/data/application/init.sql
    networks:
      - internal
networks:
  internal:
    driver: bridge
