services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_RUNMIGRATIONS: true
    networks:
      - internal
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_BACKEND_BASE_URL: "http://backend:80"
    networks:
      - internal
    depends_on:
      - backend
  worker:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    networks:
      - internal
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      ACCEPT_EULA: Y 
      MSSQL_SA_PASSWORD: 12345Abç
      MSSQL_PID: Express
    networks:
      - internal
networks:
  internal:
    driver: bridge
