services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_HTTP_PORTS: 80
    networks:
      - internal
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y 
      MSSQL_SA_PASSWORD: 12345Abç
      MSSQL_PID: Express
    networks:
      - internal
networks:
  internal:
    driver: bridge
