// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonDexSharp.Data.Contexts;

#nullable disable

namespace MonDexSharp.Data.Migrations
{
    [DbContext(typeof(MonDexSharpDbContext))]
    [Migration("20250121014823_CreatePokemonTypeModel")]
    partial class CreatePokemonTypeModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonDexSharp.Backend.Models.PokemonSpeciesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("BaseStats", "MonDexSharp.Backend.Models.PokemonSpeciesModel.BaseStats#PokemonStatsModel", b1 =>
                        {
                            b1.Property<int>("Attack")
                                .HasColumnType("int");

                            b1.Property<int>("Defense")
                                .HasColumnType("int");

                            b1.Property<int>("HP")
                                .HasColumnType("int");

                            b1.Property<int>("SpecialAttack")
                                .HasColumnType("int");

                            b1.Property<int>("SpecialDefense")
                                .HasColumnType("int");

                            b1.Property<int>("Speed")
                                .HasColumnType("int");
                        });

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("MonDexSharp.Backend.Models.PokemonTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PokemonSpeciesModelPokemonTypeModel", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("TypesId")
                        .HasColumnType("int");

                    b.HasKey("SpeciesId", "TypesId");

                    b.HasIndex("TypesId");

                    b.ToTable("PokemonSpeciesModelPokemonTypeModel");
                });

            modelBuilder.Entity("PokemonSpeciesModelPokemonTypeModel", b =>
                {
                    b.HasOne("MonDexSharp.Backend.Models.PokemonSpeciesModel", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonDexSharp.Backend.Models.PokemonTypeModel", null)
                        .WithMany()
                        .HasForeignKey("TypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
