// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonDexSharp.Backend.Contexts;

#nullable disable

namespace MonDexSharp.Backend.Migrations
{
    [DbContext(typeof(MonDexSharpDbContext))]
    partial class MonDexSharpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonDexSharp.Backend.Models.PokemonSpeciesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("BaseStats", "MonDexSharp.Backend.Models.PokemonSpeciesModel.BaseStats#PokemonStatsModel", b1 =>
                        {
                            b1.Property<int>("Attack")
                                .HasColumnType("int");

                            b1.Property<int>("Defense")
                                .HasColumnType("int");

                            b1.Property<int>("HP")
                                .HasColumnType("int");

                            b1.Property<int>("SpecialAttack")
                                .HasColumnType("int");

                            b1.Property<int>("SpecialDefense")
                                .HasColumnType("int");

                            b1.Property<int>("Speed")
                                .HasColumnType("int");
                        });

                    b.HasKey("Id");

                    b.ToTable("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
